# ----
# Site

title: The Urban Invisibles
url: http://urbaninvisibles.com
baseurl:http://urbaninvisibles.com
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: UrbanInvisibles is an initiative to study the life and times of urban India’s blue collar workforce
author:
  name:
  email:
  twitter: invisiblesurban
  name: 
  links:
    

# -----
# Build

collections:
  staff_members:
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe src="https://donorbox.org/embed/give-sheep-the-vote?hide_donation_meter=true" height="685px" width="100%" style="max-width:425px; min-width:310px" seamless="seamless" id="dbox-form-embed" name="donorbox" frameborder="0" scrolling="no"></iframe>'
newsletter_action: "https://urbaninvisibles.us17.list-manage.com/subscribe/post?u=5a5e09dbaff72463f2e8df8ff&amp;id=01ef68ffc5"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
